### PR TITLE
Faraz Fazli - Project 2

### PR DESCRIPTION
**Pull request by farazfazli**

### CODE REVIEW

**Comment by KingDavid91** [comment]
#  RUBRIC
**Project 2 | ADI** 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) | Exceeds Expectations (3) |
|---|---|---|---|---|
| Allow the user to search by at least three different location-related criteria |x | | | n/a |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like |x | | | |
| Gather data for the search results from the database |x | | | n/a |
| Allow the user to favorite locations, and later view those favorites |x | |  | n/a |
| Incorporate Object Oriented principles into your app |x | |  | n/a |
| Contain code comments, explaining the functionality behind sections of code |x | |  | n/a |
| Include **at least 8** manual test cases in a separate text file |x | |  | n/a |
| Include automated unit tests for all non-Android code |x | |  | |
| **Bonus**: Create a review system for user feedback at each location | n/a | n/a | n/a |   |
| **Bonus**: Incorporate more advanced Material Design principles into your UI | n/a | n/a | n/a |   |
| **Bonus**: Add more complexity to the user's searches (possibly allowing more than one search criteria at a time) | n/a | n/a | n/a |   |


Notes:
Hey Faraz, there wasn't any source code in your pull request. If this isn't right, let me know and we'll update the grading.

---

## Score:
Based on the requirements, you can earn a maximum of  **16**  points on this project.

#### Your total score is: **0**


---

## PROGRESS REPORT
**Student Check-in:**

|WHAT’S GOING WELL?|STRUGGLES|DEVELOPMENT PLAN|
|---|---|---|
| | | |

**Comment by farazfazli** [comment]
Please look at the commit above, titled "Create README.md" I mentioned the following: 

# Project-2
See [https://github.com/farazfazli/MyNeighborhood/tree/master](https://github.com/farazfazli/MyNeighborhood/tree/master)

I hope that clears up any confusion!

**Comment by drew-mahrt** [comment]
@farazfazli In the future, please put any code to submit in the correct repo, we use scripts to download all of the source code, and yours wasn't in there.

@KingDavid91 Please grab his code from the repo link he gave this time.

**Comment by farazfazli** [comment]
@KingDavid91 Can you please check this?

**Comment by farazfazli** [comment]
Hi @KingDavid91, thanks for the feedback. I am letting the user search with 3 location based criteria.

```
public Cursor search(String query) {
        SQLiteDatabase db = getReadableDatabase();
        String selection = "";
        for (int i = 1; i < ALL_COLUMNS.length; i++) {
            selection += ALL_COLUMNS[i] + " LIKE ?";
            if (i < ALL_COLUMNS.length - 1) {
                selection += " OR ";
            }
        }
        String[] selectionArgs = {"%" + query + "%", "%" + query + "%", "%" + query + "%", "%" + query + "%"};
        return db.query(table, ALL_COLUMNS, selection, selectionArgs, null, null, null);
    }
```

**Pull request closed without merging**
