### PR TITLE
Rob Errera - Completed Project 2

### PR DESCRIPTION
**Pull request by roberrera**

### CODE REVIEW

**Comment by KingDavid91** [comment]
#  RUBRIC
**Project 2 | ADI** 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) | Exceeds Expectations (3) |
|---|---|---|---|---|
| Allow the user to search by at least three different location-related criteria | |x | | n/a |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like | | | |x |
| Gather data for the search results from the database | | |x | n/a |
| Allow the user to favorite locations, and later view those favorites | | | x | n/a |
| Incorporate Object Oriented principles into your app | | | x | n/a |
| Contain code comments, explaining the functionality behind sections of code | | | x | n/a |
| Include **at least 8** manual test cases in a separate text file | | | x | n/a |
| Include automated unit tests for all non-Android code | | | x | |
| **Bonus**: Create a review system for user feedback at each location | n/a | n/a | n/a | x  |
| **Bonus**: Incorporate more advanced Material Design principles into your UI | n/a | n/a | n/a | -  |
| **Bonus**: Add more complexity to the user's searches (possibly allowing more than one search criteria at a time) | n/a | n/a | n/a | -  |


Notes:
Hey Rob, great app. I like the structure you created to separate your classes from your activities and your support classes. This is an important concept to incorporate in your code structure to keep your resources as decoupled as possible, especially in large scale enterprise applications. One thing I would work on is using optimized image sizes (especially when it comes to mobile applications). This will ensure that your application runs smoothly on any user device and not just your device. There are several resources online that can optimize any image you want to use in your application so you avoid Out of Memory exceptions.

---

## Score:
Based on the requirements, you can earn a maximum of  **16**  points on this project.

#### Your total score is: **16**


---

## PROGRESS REPORT
**Student Check-in:**

|WHAT’S GOING WELL?|STRUGGLES|DEVELOPMENT PLAN|
|---|---|---|
| | | |

**Comment by roberrera** [comment]
Thanks for the feedback, David! I'm a bit confused about why the first requirement "does not meet expectations":
> Allow the user to search by at least three different location-related criteria
I set up the code so you can search the name of the place, the address, and the type of place (cafe, etc.). What did I miss for this requirement?

**Comment by KingDavid91** [comment]
When I was running your application, I didn't get any search results for at least three different location-related criteria. I was only able to search by the name and the address but I'll try again in a bit and update the appropriate change.

**Comment by roberrera** [comment]
Ok, thanks. If you search for cafe, bar, pizzeria (i.e. type of place) that should check off your third search criteria.

**Pull request closed without merging**
